apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: starlabs
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jdpahl122/star-labs:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: starlabs
  name: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: starlabs
  name: frontend
  annotations:
    kubernetes.io/ingress.class:    nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 5g

spec:
  tls:
    - secretName: star-labs-tls
      hosts:
        - starlabs.apps.jonpahl.com
  rules:
    - host: starlabs.apps.jonpahl.com
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
